# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IXFDO6336S3dx432c8hN53TBgDIXFN4E
"""

import pandas as pd
import torch
import time
from torch.utils.data import DataLoader, TensorDataset

def load_data(file_path):
    df = pd.read_csv(file_path)

    token_cols = [f'token_{i:02d}' for i in range(1, 21)]
    sequences = torch.tensor(df[token_cols].values, dtype=torch.long)

    labels = torch.tensor(df['label'].values, dtype=torch.float32)

    return TensorDataset(sequences, labels)

train_dataset = load_data('train.csv')
val_dataset = load_data('validation.csv')
test_dataset = load_data('test.csv')

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32)
test_loader = DataLoader(test_dataset, batch_size=32)

print(f"Data Loaded Successfully! Training samples: {len(train_dataset)}")