# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yfUrWcOl-1Kn-LIIjDNrcGMHPCEiYyyv
"""

import torch.nn as nn
import math

class PositionalEncoding(nn.Module):
    def __init__(self, d_model, max_len=20):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float).unsqueeze(1)
        div_term = torch.exp(torch.arange(0, d_model, 2).float() * (-math.log(10000.0) / d_model))

        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)

        self.register_buffer('pe', pe.unsqueeze(0))

    def forward(self, x):
        # x shape: [batch_size, seq_len, d_model]
        return x + self.pe[:, :x.size(1)]

class MultiHeadAttention(nn.Module):
    def __init__(self, d_model, num_heads):
        super().__init__()
        self.num_heads = num_heads
        self.d_model = d_model
        assert d_model % num_heads == 0

        self.depth = d_model // num_heads

        self.wq = nn.Linear(d_model, d_model)
        self.wk = nn.Linear(d_model, d_model)
        self.wv = nn.Linear(d_model, d_model)

        self.dense = nn.Linear(d_model, d_model)

    def split_heads(self, x, batch_size):
        x = x.view(batch_size, -1, self.num_heads, self.depth)
        return x.transpose(1, 2)

    def forward(self, q, k, v, mask=None):
        batch_size = q.size(0)

        q = self.split_heads(self.wq(q), batch_size)
        k = self.split_heads(self.wk(k), batch_size)
        v = self.split_heads(self.wv(v), batch_size)

        matmul_qk = torch.matmul(q, k.transpose(-1, -2))
        dk = torch.tensor(self.depth, dtype=torch.float32)
        scaled_attention_logits = matmul_qk / torch.sqrt(dk)

        if mask is not None:
            scaled_attention_logits = scaled_attention_logits.masked_fill(mask == 0, -1e9)

        attention_weights = torch.softmax(scaled_attention_logits, dim=-1)
        output = torch.matmul(attention_weights, v)

        output = output.transpose(1, 2).contiguous()
        output = output.view(batch_size, -1, self.d_model)

        return self.dense(output)

class TransformerBlock(nn.Module):
    def __init__(self, d_model, num_heads, ff_dim, dropout=0.1):
        super().__init__()
        # 1. Multi-head Self-attention
        self.mha = MultiHeadAttention(d_model, num_heads)

        # 2. Feed-forward Network
        self.ffn = nn.Sequential(
            nn.Linear(d_model, ff_dim),
            nn.ReLU(),
            nn.Linear(ff_dim, d_model)
        )

        # 3. Layer Normalization
        self.layernorm1 = nn.LayerNorm(d_model)
        self.layernorm2 = nn.LayerNorm(d_model)

        # 4. Dropout
        self.dropout = nn.Dropout(dropout)

    def forward(self, x, mask=None):
        # Attention + Residual Connection + LayerNorm
        attn_output = self.mha(x, x, x, mask)
        x = self.layernorm1(x + self.dropout(attn_output))

        # Feed-forward + Residual Connection + LayerNorm
        ffn_output = self.ffn(x)
        x = self.layernorm2(x + self.dropout(ffn_output))

        return x

class MiniTransformer(nn.Module):
    def __init__(self, vocab_size, d_model, num_heads, ff_dim, num_layers, max_len=20):
        super().__init__()
        self.embedding = nn.Embedding(vocab_size, d_model)
        self.pos_encoding = PositionalEncoding(d_model, max_len)

        self.blocks = nn.ModuleList([
            TransformerBlock(d_model, num_heads, ff_dim) for _ in range(num_layers)
        ])

        # Classification head
        self.fc = nn.Linear(d_model, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        mask = (x != 0).unsqueeze(1).unsqueeze(2)

        x = self.embedding(x)
        x = self.pos_encoding(x)

        for block in self.blocks:
            x = block(x, mask)

        mask_for_mean = (x != 0).any(dim=-1).unsqueeze(-1)
        x = (x * mask_for_mean).sum(dim=1) / mask_for_mean.sum(dim=1)

        x = self.fc(x)
        return self.sigmoid(x)

class MiniTransformerNoPos(MiniTransformer):
    def forward(self, x):
        mask = (x != 0).unsqueeze(1).unsqueeze(2)
        x = self.embedding(x)

        for block in self.blocks:
            x = block(x, mask)
        mask_for_mean = (x != 0).any(dim=-1).unsqueeze(-1)
        x = (x * mask_for_mean).sum(dim=1) / mask_for_mean.sum(dim=1)
        x = self.fc(x)
        return self.sigmoid(x)